from . import marketplace_config
from . import product_template
from . import product_product
from . import res_partner
from . import sale_order
from . import stock_move
from . import marketplace_api
from . import marketplace_sync_log
from . import marketplace_order_processor
